package audio

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestMain(m *testing.M) {
	if mode := os.Getenv("YAP_TEST_AUDIO_DECODER"); mode != "" {
		if len(os.Args) == 2 && os.Args[1] == "--shimgen-help" {
			fmt.Printf("This is a shim, generated by Chocolatey's ShimGenerator (shimgen).\n Target: '%s'\n", os.Getenv("YAP_TEST_DECODER_TARGET"))
			os.Exit(1)
		}
		args := map[string]string{}
		for i, arg := range os.Args[:len(os.Args)-1] {
			if strings.HasPrefix(arg, "-") {
				args[arg] = os.Args[i+1]
			}
		}
		if args["-protocol_whitelist"] != "file,pipe" || args["-map"] != "0:a:0" || args["-ar"] != "16000" || args["-ac"] != "1" || args["-c:a"] != "pcm_s16le" || args["-f"] != "s16le" {
			os.Exit(3)
		}
		input := args["-i"]
		data, _ := os.ReadFile(input)
		if filepath.Base(input) != "input.mp3" || string(data) != "compressed fixture" {
			os.Exit(4)
		}
		os.WriteFile(os.Getenv("YAP_TEST_DECODER_INPUT"), []byte(input), 0600)
		switch mode {
		case "wait":
			time.Sleep(10 * time.Second)
		case "fail":
			os.Stderr.WriteString(strings.Repeat("decoder error ", 1000))
			os.Exit(2)
		case "overlong":
			io.CopyN(os.Stdout, zeroAudioReader{}, maxDecodedBytes+2)
		case "short":
			os.Stdout.Write(make([]byte, 100))
		default:
			os.Stdout.Write(make([]byte, 32000))
		}
		os.Exit(0)
	}
	os.Exit(m.Run())
}

type zeroAudioReader struct{}

func (zeroAudioReader) Read(data []byte) (int, error) { clear(data); return len(data), nil }

func decoderOutput(t *testing.T) *os.File {
	t.Helper()
	f, err := os.Create(filepath.Join(t.TempDir(), "normalized.wav"))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { f.Close() })
	return f
}

func TestCompressedImportProcessAndCleanup(t *testing.T) {
	source := filepath.Join(t.TempDir(), "private file.MP3")
	os.WriteFile(source, []byte("compressed fixture"), 0600)
	executable, _ := os.Executable()
	resolve := func() (string, error) { return executable, nil }
	for _, mode := range []string{"normal", "fail", "overlong", "short", "wait"} {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("YAP_TEST_AUDIO_DECODER", mode)
			inputLog := filepath.Join(t.TempDir(), "input.txt")
			t.Setenv("YAP_TEST_DECODER_INPUT", inputLog)
			ctx := context.Background()
			if mode == "wait" {
				var cancel context.CancelFunc
				ctx, cancel = context.WithTimeout(ctx, 200*time.Millisecond)
				defer cancel()
			}
			out := decoderOutput(t)
			duration, err := normalizeImport(ctx, source, out, resolve)
			if mode == "normal" {
				if err != nil || duration != 1000 {
					t.Fatalf("normal decode: %d %v", duration, err)
				}
				out.Seek(0, io.SeekStart)
				data, _ := io.ReadAll(out)
				if len(data) != 32044 || binary.LittleEndian.Uint32(data[40:]) != 32000 || binary.LittleEndian.Uint16(data[22:]) != 1 {
					t.Fatal("invalid normalized WAV")
				}
			} else if err == nil {
				t.Fatal("accepted failed or out-of-bounds decoding")
			}
			if mode == "wait" && !errors.Is(err, context.DeadlineExceeded) {
				t.Fatalf("decoder not cancelled: %v", err)
			}
			if mode == "overlong" && !errors.Is(err, errImportDuration) {
				t.Fatalf("duration bound: %v", err)
			}
			if mode == "fail" && len(err.Error()) > 2200 {
				t.Fatal("unbounded diagnostics")
			}
			input, _ := os.ReadFile(inputLog)
			if len(input) > 0 {
				if _, err := os.Stat(filepath.Dir(string(input))); !os.IsNotExist(err) {
					t.Fatal("private copy leaked", err)
				}
			}
			original, _ := os.ReadFile(source)
			if string(original) != "compressed fixture" {
				t.Fatal("source modified")
			}
		})
	}
}

func TestCompressedImportMissingDecoderAndFormatChecks(t *testing.T) {
	wav := importFixture(t, 1, 16, 1, 16000, 1)
	missing := func() (string, error) { return "", errors.New("FFmpeg missing") }
	if _, err := normalizeImport(context.Background(), wav, decoderOutput(t), missing); err != nil {
		t.Fatal("WAV required FFmpeg", err)
	}
	if _, err := normalizeImport(context.Background(), "source.mp3", decoderOutput(t), missing); err == nil || !strings.Contains(err.Error(), "FFmpeg missing") {
		t.Fatal(err)
	}
	called := false
	resolver := func() (string, error) { called = true; return "", nil }
	if _, err := normalizeImport(context.Background(), "playlist.m3u", decoderOutput(t), resolver); err == nil || called {
		t.Fatal("unsupported format started decoder")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := normalizeImport(ctx, wav, decoderOutput(t), resolver); !errors.Is(err, context.Canceled) {
		t.Fatal(err)
	}
	oversized := filepath.Join(t.TempDir(), "huge.mp3")
	f, _ := os.Create(oversized)
	f.Truncate(maxImportBytes + 1)
	f.Close()
	if err := snapshotImport(context.Background(), oversized, filepath.Join(t.TempDir(), "snapshot")); err == nil {
		t.Fatal("oversized source copied")
	}
	if err := snapshotImport(context.Background(), t.TempDir(), filepath.Join(t.TempDir(), "snapshot")); err == nil {
		t.Fatal("directory accepted")
	}
}

func TestFFmpegDiscoveryIncludesFinderPaths(t *testing.T) {
	var searched []string
	look := func(path string) (string, error) {
		searched = append(searched, path)
		if path == "/opt/homebrew/bin/ffmpeg" {
			return path, nil
		}
		return "", os.ErrNotExist
	}
	path, err := locateFFmpeg("darwin", "/Applications/Yap.app/Contents/MacOS/Yap", look)
	if err != nil || path != "/opt/homebrew/bin/ffmpeg" || searched[0] != filepath.Join("/Applications/Yap.app/Contents", "Resources", "ffmpeg", "ffmpeg") {
		t.Fatalf("discovery: %s %v %v", path, err, searched)
	}
	if _, err := locateFFmpeg("windows", "", func(string) (string, error) { return "", os.ErrNotExist }); err == nil || !strings.Contains(err.Error(), "Install FFmpeg") {
		t.Fatal("missing setup guidance", err)
	}
}

func TestFFmpegShimTargetValidation(t *testing.T) {
	path := filepath.Join(t.TempDir(), "shim.exe")
	target := filepath.Join(t.TempDir(), "actual ffmpeg.exe")
	help := "This is a shim, generated by Chocolatey's ShimGenerator (shimgen).\n Target: '%s'\n"
	look := func(candidate string) (string, error) {
		if candidate == target {
			return target, nil
		}
		return "", os.ErrNotExist
	}
	if got, err := ffmpegShimTarget(path, fmt.Sprintf(help, target), look); err != nil || got != target {
		t.Fatalf("target not resolved: %s %v", got, err)
	}
	for _, invalid := range []string{"ffmpeg.exe", path, filepath.Join(t.TempDir(), "missing.exe")} {
		if _, err := ffmpegShimTarget(path, fmt.Sprintf(help, invalid), look); err == nil {
			t.Fatal("accepted unsafe or missing shim target", invalid)
		}
	}
	if got, err := ffmpegShimTarget(path, "Unrecognized option 'shimgen-help'.", look); err != nil || got != path {
		t.Fatal("standalone FFmpeg rejected", got, err)
	}
}

func TestFFmpegShimCancellationUsesDirectDecoder(t *testing.T) {
	executable, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	shim := filepath.Join(t.TempDir(), "ffmpeg.exe")
	binary, err := os.ReadFile(executable)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(shim, binary, 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("YAP_TEST_AUDIO_DECODER", "wait")
	t.Setenv("YAP_TEST_DECODER_TARGET", executable)
	inputLog := filepath.Join(t.TempDir(), "input.txt")
	t.Setenv("YAP_TEST_DECODER_INPUT", inputLog)
	resolved, err := unwrapFFmpeg(context.Background(), shim)
	if err != nil || resolved != executable {
		t.Fatalf("launcher not bypassed: %s %v", resolved, err)
	}
	source := filepath.Join(t.TempDir(), "source.mp3")
	if err := os.WriteFile(source, []byte("compressed fixture"), 0600); err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()
	_, err = normalizeImport(ctx, source, decoderOutput(t), func() (string, error) { return resolved, nil })
	if !errors.Is(err, context.DeadlineExceeded) {
		t.Fatalf("direct decoder not cancelled: %v", err)
	}
	input, err := os.ReadFile(inputLog)
	if err != nil {
		t.Fatal("decoder never started", err)
	}
	if _, err := os.Stat(filepath.Dir(string(input))); !os.IsNotExist(err) {
		t.Fatal("cancelled decoder retained its private input", err)
	}
}

func TestRealFFmpegImportsSupportedFormats(t *testing.T) {
	ffmpeg, err := findFFmpeg(context.Background())
	if err != nil {
		t.Skip("local FFmpeg not installed")
	}
	source := importFixture(t, 1, 16, 2, 48000, 1)
	formats := []struct{ ext, codec string }{{"mp3", "libmp3lame"}, {"m4a", "aac"}, {"aac", "aac"}, {"flac", "flac"}, {"ogg", "libvorbis"}, {"opus", "libopus"}, {"aiff", "pcm_s16be"}, {"wma", "wmav2"}}
	for _, format := range formats {
		t.Run(format.ext, func(t *testing.T) {
			input := filepath.Join(t.TempDir(), "audio file."+format.ext)
			ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
			defer cancel()
			cmd := exec.CommandContext(ctx, ffmpeg, "-hide_banner", "-loglevel", "error", "-nostdin", "-i", source, "-c:a", format.codec, input)
			if log, err := cmd.CombinedOutput(); err != nil {
				t.Fatalf("make %s fixture: %v %s", format.ext, err, log)
			}
			before, _ := os.ReadFile(input)
			out := decoderOutput(t)
			duration, err := NormalizeImport(ctx, input, out)
			if err != nil || duration < 950 || duration > 1200 {
				t.Fatalf("decode %s: %d %v", format.ext, duration, err)
			}
			out.Seek(0, io.SeekStart)
			data, _ := io.ReadAll(out)
			if len(data) < 44 || binary.LittleEndian.Uint32(data[24:]) != 16000 || binary.LittleEndian.Uint16(data[22:]) != 1 || int(binary.LittleEndian.Uint32(data[40:])) != len(data)-44 {
				t.Fatal("incorrect canonical audio")
			}
			after, _ := os.ReadFile(input)
			if !bytes.Equal(before, after) {
				t.Fatal("original changed")
			}
		})
	}
}
