package audio

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"yap/internal/process"
)

// Input formats are selected explicitly: an audio file cannot become a playlist
// or a network input merely because its contents resemble another format.
var importFormats = map[string]string{
	".mp3": "mp3", ".m4a": "mov", ".aac": "aac", ".flac": "flac",
	".ogg": "ogg", ".opus": "ogg", ".aif": "aiff", ".aiff": "aiff", ".wma": "asf",
}

const ImportFilePattern = "*.wav;*.mp3;*.m4a;*.aac;*.flac;*.ogg;*.opus;*.aif;*.aiff;*.wma"
const maxDecodedBytes int64 = 16000 * 2 * 600

var errImportDuration = errors.New("choose audio between 0.3 seconds and 10 minutes")
var ErrFFmpegMissing = errors.New("this audio format requires local FFmpeg. Install FFmpeg, add it to PATH, and reopen Yap. On macOS, Homebrew's default install is also detected. WAV import works without FFmpeg")

// ImportDecoder checks the selected file before offering a download. Local
// installations take precedence; managed is the application's private decoder.
func ImportDecoder(ctx context.Context, source, managed string) (string, error) {
	ext := strings.ToLower(filepath.Ext(source))
	if ext != ".wav" && importFormats[ext] == "" {
		return "", errors.New("choose WAV, MP3, M4A, AAC, FLAC, OGG, Opus, AIFF, or WMA audio")
	}
	info, err := os.Stat(source)
	if err != nil {
		return "", err
	}
	if !info.Mode().IsRegular() || info.Size() > maxImportBytes {
		return "", errors.New("choose a regular audio file smaller than 256 MiB")
	}
	if ext == ".wav" {
		return "", nil
	}
	return FindFFmpeg(ctx, managed)
}

// FindFFmpeg uses the same discovery order for imports and Settings.
func FindFFmpeg(ctx context.Context, managed string) (string, error) {
	path, err := findFFmpeg(ctx)
	if errors.Is(err, ErrFFmpegMissing) && managed != "" {
		return managed, nil
	}
	return path, err
}

// NormalizeImportWithFFmpeg uses a preselected decoder, keeping WAV independent.
func NormalizeImportWithFFmpeg(ctx context.Context, source string, destination io.WriteSeeker, executable string) (int64, error) {
	return normalizeImport(ctx, source, destination, func() (string, error) {
		if executable != "" {
			return executable, nil
		}
		return findFFmpeg(ctx)
	})
}

// NormalizeImport preserves the dependency-free WAV path. Other formats use a
// locally installed decoder and stream bounded PCM into the owned recording.
func NormalizeImport(ctx context.Context, source string, destination io.WriteSeeker) (int64, error) {
	return normalizeImport(ctx, source, destination, func() (string, error) { return findFFmpeg(ctx) })
}

func normalizeImport(ctx context.Context, source string, destination io.WriteSeeker, decoder func() (string, error)) (duration int64, err error) {
	if err := ctx.Err(); err != nil {
		return 0, err
	}
	extension := strings.ToLower(filepath.Ext(source))
	if extension == ".wav" {
		return NormalizeFile(ctx, source, destination)
	}
	format, supported := importFormats[extension]
	if !supported {
		return 0, errors.New("choose WAV, MP3, M4A, AAC, FLAC, OGG, Opus, AIFF, or WMA audio")
	}
	executable, err := decoder()
	if err != nil {
		return 0, err
	}
	// A seekable private snapshot supports M4A files with metadata at the end,
	// binds decoding to the selected file, and bounds actual source bytes.
	dir, err := os.MkdirTemp("", "yap-audio-import-")
	if err != nil {
		return 0, err
	}
	defer func() {
		if cleanupErr := os.RemoveAll(dir); cleanupErr != nil {
			err = errors.Join(err, fmt.Errorf("could not remove temporary audio: %w", cleanupErr))
		}
	}()
	input := filepath.Join(dir, "input"+extension)
	if err = snapshotImport(ctx, source, input); err != nil {
		return 0, err
	}
	return decodeImport(ctx, executable, input, format, destination)
}

func findFFmpeg(ctx context.Context) (string, error) {
	executable, _ := os.Executable()
	path, err := locateFFmpeg(runtime.GOOS, executable, exec.LookPath)
	if err != nil || runtime.GOOS != "windows" {
		return path, err
	}
	return unwrapFFmpeg(ctx, path)
}

// Chocolatey launchers spawn a separate decoder which a launcher-only kill
// cannot stop. Their help switch reports the target without running it.
func unwrapFFmpeg(ctx context.Context, path string) (string, error) {
	probe, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	cmd := exec.CommandContext(probe, path, "--shimgen-help")
	process.Hide(cmd)
	cmd.WaitDelay = time.Second
	log := &decoderLog{limit: 8192}
	cmd.Stdout, cmd.Stderr = log, log
	_ = cmd.Run() // Real FFmpeg rejects this switch; shims may exit nonzero too.
	if err := probe.Err(); err != nil {
		return "", err
	}
	return ffmpegShimTarget(path, string(log.data), exec.LookPath)
}

func ffmpegShimTarget(path, help string, lookPath func(string) (string, error)) (string, error) {
	if !strings.Contains(help, "This is a shim, generated by Chocolatey's ShimGenerator") {
		return path, nil
	}
	for _, line := range strings.Split(help, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "Target: '") && strings.HasSuffix(line, "'") {
			target := strings.TrimSuffix(strings.TrimPrefix(line, "Target: '"), "'")
			if filepath.IsAbs(target) && !strings.EqualFold(filepath.Clean(target), filepath.Clean(path)) {
				if resolved, err := lookPath(target); err == nil {
					return resolved, nil
				}
			}
		}
	}
	return "", errors.New("could not locate FFmpeg behind its Chocolatey launcher. Reinstall FFmpeg or place the actual ffmpeg.exe beside Yap")
}

func locateFFmpeg(platform, executable string, lookPath func(string) (string, error)) (string, error) {
	name := "ffmpeg"
	if platform == "windows" {
		name += ".exe"
	}
	candidates := []string{}
	if executable != "" {
		if platform == "darwin" && filepath.Base(filepath.Dir(executable)) == "MacOS" && filepath.Base(filepath.Dir(filepath.Dir(executable))) == "Contents" {
			candidates = append(candidates, filepath.Join(filepath.Dir(filepath.Dir(executable)), "Resources", "ffmpeg", "ffmpeg"))
		} else {
			candidates = append(candidates, filepath.Join(filepath.Dir(executable), name))
		}
	}
	candidates = append(candidates, name)
	// Finder-launched macOS apps normally don't inherit the shell's Homebrew PATH.
	if platform == "darwin" {
		candidates = append(candidates, "/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg")
	}
	for _, candidate := range candidates {
		if path, err := lookPath(candidate); err == nil {
			return path, nil
		}
	}
	return "", ErrFFmpegMissing
}

func snapshotImport(ctx context.Context, source, destination string) error {
	info, err := os.Stat(source)
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Size() > maxImportBytes {
		return errors.New("choose a regular audio file smaller than 256 MiB")
	}
	input, err := os.Open(source)
	if err != nil {
		return err
	}
	defer input.Close()
	info, err = input.Stat()
	if err != nil {
		return err
	}
	if !info.Mode().IsRegular() || info.Size() > maxImportBytes {
		return errors.New("choose a regular audio file smaller than 256 MiB")
	}
	output, err := os.OpenFile(destination, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	n, err := io.Copy(output, io.LimitReader(importReader{ctx, input}, maxImportBytes+1))
	err = errors.Join(err, output.Close())
	if n > maxImportBytes {
		return errors.New("audio file exceeds 256 MiB")
	}
	return err
}

type importReader struct {
	ctx    context.Context
	reader io.Reader
}

func (r importReader) Read(data []byte) (int, error) {
	if err := r.ctx.Err(); err != nil {
		return 0, err
	}
	return r.reader.Read(data)
}

func decodeImport(ctx context.Context, executable, input, format string, destination io.WriteSeeker) (int64, error) {
	if err := ctx.Err(); err != nil {
		return 0, err
	}
	if err := Header(destination, 0); err != nil {
		return 0, err
	}
	child, cancel := context.WithCancel(ctx)
	defer cancel()
	args := []string{"-hide_banner", "-loglevel", "error", "-nostdin", "-xerror", "-protocol_whitelist", "file,pipe", "-f", format}
	if format == "mov" {
		args = append(args, "-enable_drefs", "0", "-use_absolute_path", "0")
	}
	args = append(args, "-i", input, "-map", "0:a:0", "-vn", "-sn", "-dn", "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", "-f", "s16le", "pipe:1")
	cmd := exec.CommandContext(child, executable, args...)
	process.Hide(cmd)
	// Bound inherited-pipe waits; normal FFmpeg is a single foreground process.
	cmd.WaitDelay = 2 * time.Second
	output := &decodedPCMWriter{destination: destination, cancel: cancel}
	log := &decoderLog{}
	cmd.Stdout, cmd.Stderr = output, log
	err := cmd.Run()
	if ctx.Err() != nil {
		return 0, ctx.Err()
	}
	if output.err != nil {
		return 0, output.err
	}
	if err != nil {
		return 0, fmt.Errorf("could not decode audio with FFmpeg: %w%s", err, log.message())
	}
	if output.bytes < 9600 || output.bytes%2 != 0 {
		return 0, errImportDuration
	}
	if _, err := destination.Seek(0, io.SeekStart); err != nil {
		return 0, err
	}
	if err := Header(destination, uint32(output.bytes)); err != nil {
		return 0, err
	}
	return output.bytes * 1000 / 32000, nil
}

type decodedPCMWriter struct {
	destination io.Writer
	cancel      context.CancelFunc
	bytes       int64
	err         error
}

func (w *decodedPCMWriter) Write(data []byte) (int, error) {
	if int64(len(data)) > maxDecodedBytes-w.bytes {
		w.err = errImportDuration
		w.cancel()
		return 0, w.err
	}
	n, err := w.destination.Write(data)
	w.bytes += int64(n)
	if err == nil && n != len(data) {
		err = io.ErrShortWrite
	}
	if err != nil {
		w.err = err
		w.cancel()
	}
	return n, err
}

// FFmpeg diagnostics are bounded independently of input size or runtime.
type decoderLog struct {
	data  []byte
	limit int
}

func (l *decoderLog) Write(data []byte) (int, error) {
	n := len(data)
	limit := l.limit
	if limit == 0 {
		limit = 2000
	}
	if len(data) >= limit {
		l.data = append(l.data[:0], data[len(data)-limit:]...)
	} else {
		l.data = append(l.data, data...)
		if len(l.data) > limit {
			l.data = append(l.data[:0], l.data[len(l.data)-limit:]...)
		}
	}
	return n, nil
}
func (l *decoderLog) message() string {
	if message := strings.TrimSpace(string(l.data)); message != "" {
		return "\n" + message
	}
	return ""
}
